"""
patcher.py

Applies unified diff patches generated by the LLM.

Features:
- Creates backup before modifying files
- Applies unified diff patches
- Restores original file if patch fails
"""

import shutil
from pathlib import Path
from unidiff import PatchSet


class PatchApplier:
    """
    Applies unified diff patches to project files.
    """

    def __init__(self, repository_path: str):
        self.repository_path = Path(repository_path)

    def create_backup(self, file_path: str):
        """
        Create a backup of a file before modification.
        """

        source = self.repository_path / file_path

        backup = source.with_suffix(source.suffix + ".bak")

        shutil.copy2(source, backup)

        return backup

    def restore_backup(self, file_path: str):
        """
        Restore backup if something goes wrong.
        """

        source = self.repository_path / file_path

        backup = source.with_suffix(source.suffix + ".bak")

        if backup.exists():
            shutil.copy2(backup, source)
            backup.unlink()

    def remove_backup(self, file_path: str):
        """
        Remove backup after successful patch.
        """

        backup = (
            self.repository_path / file_path
        ).with_suffix(
            Path(file_path).suffix + ".bak"
        )

        if backup.exists():
            backup.unlink()

    def apply_patch(self, patch_text: str):
        """
        Apply a unified diff patch.

        Returns
        -------
        bool
            True if patch applied successfully.
        """

        try:

            patch = PatchSet(patch_text.splitlines(True))

            for patched_file in patch:

                relative_path = patched_file.path

                file_path = self.repository_path / relative_path

                if not file_path.exists():
                    print(f"File not found: {relative_path}")
                    continue

                self.create_backup(relative_path)

                original_lines = file_path.read_text(
                    encoding="utf-8",
                    errors="ignore"
                ).splitlines(True)

                new_lines = []
                index = 0

                for hunk in patched_file:

                    # Copy unchanged lines before hunk
                    while index < hunk.source_start - 1:
                        new_lines.append(original_lines[index])
                        index += 1

                    for line in hunk:

                        if line.is_context:
                            new_lines.append(line.value)
                            index += 1

                        elif line.is_removed:
                            index += 1

                        elif line.is_added:
                            new_lines.append(line.value)

                # Append remaining lines
                new_lines.extend(original_lines[index:])

                file_path.write_text(
                    "".join(new_lines),
                    encoding="utf-8"
                )

                self.remove_backup(relative_path)

            return True

        except Exception as e:

            print("Patch failed:")
            print(e)

            for patched_file in patch:
                self.restore_backup(patched_file.path)

            return False